import back1 from  "../assets/back.png"
import cup1 from  "../assets/cup.png"
import image1 from  "../assets/image.png"
import line1 from  "../assets/line.png"
import night1 from  "../assets/night.png"
import sun1 from  "../assets/sun.png"
export const back =back1;
export const cup =cup1;
export const image =image1;
export const line =line1;
export const night =night1;
export const sun =sun1;
